---

galaxy_info:
  author: Felix Kazuya, macwinnie
  description: Install the Amazon Command Line Interace

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: CC-BY

  min_ansible_version: 2.0

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

...
