---

# by default, this role will use user groups for checking SSH permissions
ssh_users_instead_groups: false

# define the groups permitted to login via SSH
ssh_groups:
  - ssh_users

# prepare empty variables for ssh allowed and disallowed users
ssh_users:   []
nossh_users: []

# default values for sshd configuration
sshd:
  port:                              '{{ ssh_port | default("22") }}'
  listen_address:                    '{{ ssh_listen_address | default ( ansible_default_ipv4.address ) }}'
  protocol:                          '2'
  host_key:                          '/etc/ssh/ssh_host_rsa_key'
  syslog_facility:                   'AUTH'
  log_level:                         'INFO'
  login_grace_time:                  '2m'
  permit_root_login:                 'no'
  max_auth_tries:                    '6'
  max_sessions:                      '10'
  strict_modes:                      'yes'
  pubkey_authentication:             'yes'
  ignore_rhosts:                     'yes'
  hostbased_authentication:          'no'
  permit_empty_passwords:            'no'
  challenge_response_authentication: 'no'
  password_authentication:           'no'
  x11_forwarding:                    'no'
  x11_display_offset:                '10'
  print_motd:                        '{{ sshd_print_motd | default("no") }}'
  print_last_log:                    'yes'
  tcp_keep_alive:                    'yes'
  accept_env:                        'LANG LC_*'
  use_pam:                           'yes'
  client_alive_count_max:            '24'
  client_alive_interval:             '3600'
  banner:                            'none'
  allow_agent_forwarding:            'yes'
  allow_tcp_forwarding:              'yes'
  gateway_ports:                     'no'
  x11_use_localhost:                 'yes'
  permit_tty:                        'yes'
  permit_user_environment:           'no'
  compression:                       'delayed'
  use_dns:                           'no'
  pid_file:                          '/var/run/sshd.pid'
  max_startups:                      '10:30:100'
  permit_tunnel:                     'no'
  chroot_directory:                  'none'
  version_addendum:                  'none'

# dependency tools
package_state: "latest"
ssh_tools:
  - name: "mosh"
  - name: "ufw"
  - name: "lsof"
  - name: "sudo"
  - name: "logrotate"

mosh:
  install_path: '{{ mosh_install_path | default("/usr/bin") }}'
  script_path:  '{{ mosh_script_path | default("/usr/local/bin") }}'
  script_name:  'mosh-allow-ufw'
  server_name:  'mosh-server'
  debug:        '{{ mosh_debug | default("yes") }}'
  logfile:      '/var/log/mosh_ufw.log'
  logrot:
    time:       'weekly'
    rotate:     '5'
    path:       '/etc/logrotate.d/'

mosh_path_order_regex: '(^|.*:)({{ mosh.script_path | regex_escape() }}):(.*:)?({{ mosh.install_path | regex_escape() }})(:.*|$)'

...
