---

- name: Ensure configs are installed
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
  become: yes
  with_items:
    - 10periodic
    - 50unattended-upgrades

...
