---

# build the stack dictionary
- set_fact:
    stack: "{{ { \"name\" : cur_stack.key } | combine( cur_stack.value ) }}"
  when: "'name' not in cur_stack.value"

- set_fact:
    stack: "{{ cur_stack.value }}"
  when: "'name' in cur_stack.value"

# Now run the stack
- name: "run stack \"{{ cur_stack.key }}\""
  import_role:
    name: docker_stack
  vars:
    stack: stack

...
