#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
###

- name:  'deploy docker stacks'
  hosts: 'docker_hosts:docker:!localhost'
  become: yes

  tasks:
    - name: 'create logrotate config'
      include_role:
        name: logrotate
      when: logrotate is defined

    # include_* is processed in place, import_* would be pre-processed, so it should not be used here.
    - include_tasks: "_prepare.yml"

    # Træfik check now has to take place
    - name: check Træfik run state
      include_tasks: "_check_traefik.yml"
      with_dict: "{{ docker_stacks }}"
      loop_control:
        loop_var: cur_stack

    - name: Run Træfik
      include_role:
        name: docker_stack_traefik
      when: run_traefik | default(False) | bool

    # Afer that, run all Docker Stacks
    - name: Run Docker stacks
      include_tasks: "_run.yml"
      with_dict: "{{ docker_stacks }}"
      loop_control:
        loop_var: cur_stack
      when: docker_stacks | length != 0

...
