---

# use the `docker-compose` folder below the execution folder `ansible`
composerFilePath: "docker-compose"

DOCKER_PROXYNET:  "proxy"
DOCKER_DBNET:     "database"
DOCKER_WORLDNET:  "publicwww"
traefik_network:  "proxy"

remote:           false
debug:            false

docker_default_restart_policy: 'unless-stopped'

docker_logging:
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "5"

...
