---

- name: Delete swap from fstab
  lineinfile:
    dest: /etc/fstab 
    line: "{{ swapfile }} none swap defaults 0 0"
    state: absent

- name: Do some magic
  shell: echo "3" > /proc/sys/vm/drop_caches

- name: Disable swap
  command: swapoff -a

- name: Delete swapfile
  file:
    path: "{{ swapfile }}"
    owner: root
    group: root
    mode: 0600
    state: absent

...