---

- name: Check if swap file exists
  stat:
    path: "{{ swapfile }}"
  register: st

- name: Check if swap file has the right size
  shell: stat -c %s {{ swapfile }}
  when: st.stat.exists
  register: size

- name: If swap file has wrong size, delete it
  include: delete_swap.yml
  when: st.stat.exists and size.stdout|int != {{ swapsize * 1024 * 1024 }}

- name: If no swap file exsists, create one
  include: create_swap.yml
  when: not st.stat.exists or size.stdout|int != {{ swapsize * 1024 * 1024 }}

...