---

- name: merge global_ufw_rules and host_ufw_rules into ufw_rules
  set_fact:
    ufw_rules: "{{ global_ufw_rules | default([]) + host_ufw_rules | default([]) }}"

- name: root block
  block:

    - name: Install ufw as firewall
      package:
        name: "{{ item.name }}"
        state: "{{ item.state | default( package_state ) }}"
      with_items: "{{ install_packages }}"
      retries: 3
      delay: 10
      when: install_ufw is not defined or install_ufw | bool

    - name: Configure ufw defaults
      ufw:
        direction: "{{ item.direction }}"
        policy:    "{{ item.policy }}"
      with_items: "{{ ufw_defaults }}"
      when: configure_ufw is not defined or configure_ufw | bool
      retries: 3
      delay: 10

    - name: Configure ufw rules
      ufw:
        rule:  "{{ item.rule }}"
        port:  "{{ item.port | default( none ) }}"
        proto: "{{ item.proto | default('tcp') }}"
        src:   "{{ item.src | default('any') }}"
        dest:  "{{ item.dest | default('any') }}"
      with_items: "{{ ufw_rules }}"
      when: ( configure_ufw is not defined or configure_ufw | bool ) and ufw_rules is defined and ufw_rules | length > 0
      retries: 3
      delay: 10

    - name: restart ufw
      service:
        name:  ufw
        state: restarted
      when: restart_ufw is not defined or restart_ufw | bool
      retries: 3
      delay: 10

    - name: enable ufw
      command: ufw --force enable
      when: enable_ufw  is not defined or enable_ufw  | bool
      retries: 3
      delay: 10

  become: true

...
