---

# prepare tmp directory
- name: Create /tmp/ssm if it does not exist
  file:
    path: /tmp/ssm
    state: directory
    mode: '0755'

# determine architecture
- name: determine architecture
  shell: dpkg --print-architecture
  register: architecture

# set architecture link part
- name: set architecture link part
  set_fact:
    # architecturelink: "{% if 'arm' in architecture.stdout %}linux_arm64{% elif 'i386' in architecture.stdout %}linux_386{% else %}linux_amd64{% endif %}"
    architecturelink: "{% if 'arm' in architecture.stdout %}debian_arm{% else %}debian_amd64{% endif %}"

# download ssm agent installer
- name: Download SSM agent installer
  get_url:
    # url: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/{{ architecturelink }}/amazon-ssm-agent.rpm"
    url: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/{{ architecturelink }}/amazon-ssm-agent.deb"
    dest: /tmp/ssm/amazon-ssm-agent.deb
    mode: '0770'

# install ssm agent
- name: install SSM agent
  command: dpkg -i /tmp/ssm/amazon-ssm-agent.deb

# stop the SSM agent
- name: stop ssm agent
  service:
    name: amazon-ssm-agent
    state: stopped

# remove ssm installer
- name: Remove /tmp/ssm since it is no more needed
  file:
    path: /tmp/ssm
    state: absent

...
