---

galaxy_info:
  author: macwinnie
  description: Deploy containerd to host

  license: CC-BY

  min_ansible_version: 2.0

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

...
