#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
###

- name:  'Create Composefiles for Hosts'
  hosts: 'docker_hosts:docker:!localhost'
  become: true

  tasks:
    - name: 'create logrotate config'
      include_role:
        name: logrotate
      when: logrotate is defined

    - name: "Deploy Traefik"
      include_role:
        name: docker_stack_traefik
      when: traefik_enabled is defined and traefik_enabled

...
