#!/usr/bin/env ansible-playbook
---

###
## Licenced unter CC-BY
##
## for this role to be run for the first time on a new pi use this command:
##
## ansible-playbook -e 'ansible_port=22 ansible_user=pi ansible_ssh_pass=raspberry ansible_sudo_pass=raspberry' -i environments/production playbooks/server/raspy.yml
##
## after the first run, the regular call is
##
## ansible-playbook -K -i environments/production playbooks/server/raspy.yml
###

# do the base provisioning for a production
- import_playbook: raspi.yml

- name: "provisioning remote controll raspberries"
  hosts: bbpi
  become: true

  tasks:

    - name: 'install additional things for AWS SSM usage'
      include_role:
        name: prepare_aws_ssm

    - name: Insert/Update WiFi Configuration
      blockinfile:
        path: /etc/wpa_supplicant/wpa_supplicant.conf
        block: |
          network={
            ssid="{{ bbpi.ssid }}"
            psk="{{ bbpi.wifipw }}"
            key_mgmt=WPA-PSK
          }

    # install teamviewer
    - name: get teamviewer
      get_url:
        url: "https://download.teamviewer.com/download/linux/teamviewer-host_armhf.deb"
        dest: /tmp/teamviewer-host_armhf.deb
        mode: '0770'
    - name: install teamviewer
      shell: dpkg -i /tmp/teamviewer-host_armhf.deb; apt-get -y --fix-broken install
      ignore_errors: true
    - name: Remove teamviewer installer since it is no more needed
      file:
        path: /tmp/teamviewer-host_armhf.deb
        state: absent
    - name: Set TeamViewer password
      shell: "teamviewer passwd '{{ bbpi.teamviewerpw }}'"


...
