#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
###

- name:  'Create Composefiles for Hosts'
  hosts: 'docker_hosts:docker:!localhost'
  become: true

  tasks:
    - debug:
        msg: "{{ app }}"
      with_dict: "{{ applications }}"
      loop_control:
        loop_var: app

    - name: "Create Docker-Compose-Files"
      include_role:
        name: create_docker_compose
      with_dict: "{{ applications }}"
      loop_control:
        loop_var: app

...
