---

package_state: 'latest'

motd_basic_tools:
  - name: 'figlet'
  - name: 'lolcat'
  - name: 'boxes'

motd_dir:           '/etc/update-motd.d/'
motd_dir_mode:      '0755'
backup_destination: '/etc/'

remove_existing_motd: no

# http://manpages.ubuntu.com/manpages/focal/man5/update-motd.5.html
motd_templates:
  00-00header: |
    #!/usr/bin/env bash

    export LANG="en_US.UTF-8"

    printf "\n"
    figlet "{{ motd_servername | default( "$( hostname | sed 's/\w\+/\L\u&/g' )" ) }}" | /usr/games/lolcat -f

    {% if motd_organisation is defined and motd_organisation != '' %}
    printf "\n"
    figlet -fsmall "{{ motd_organisation }}" | /usr/games/lolcat -f
    {% endif %}

    {% if motd_unicorn_description is defined and motd_unicorn_description != '' %}
    printf "\n"
    motd_server_description="{{ motd_unicorn_description }}"
    folded_description="$( fold -w {{ unicorn_max_len | default( 30 ) }} -s <<< "${motd_server_description}" )"
    boxes -a c -d unicornthink <<< "${folded_description}" | /usr/games/lolcat -f
    {% endif %}

    {% if motd_description is defined and motd_description != '' %}
    printf "\n"
    motd_server_description="{{ motd_description }}"
    folded_description="$( fold -w {{ description_max_len | default( 80 ) }} -s <<< "${motd_server_description}" )"
    echo "${folded_description}"
    {% endif %}

...
