---

- name: Define install env
  # k3s_install_env:
  #   - name: K3S_URL
  #     value: https://myserver:6443
  #   - name: K3S_TOKEN
  #     value: mynodetoken
  ansible.builtin.set_fact:
    final_k3s_install_env: "{{ final_k3s_install_env }} {{ item.key }}=\"{{ item.value }}\""
  loop: "{{ k3s_install_env | dict2items }}"
  when:
    - k3s_install_env is defined
    - k3s_install_env | length > 0
  tags:
    - k3s

- name: "Install all prerequisite tools needed for this install routine"
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default( package_state) }}"
  with_items: "{{ install_k3s.prerequisites }}"
  tags:
    - k3s
    - packages

- name: "Install k3s"
  ansible.builtin.include_tasks: _k3s_install.yml
  tags:
    - k3s

- name: "Install CNI"
  ansible.builtin.include_tasks: _k3s_cni.yml
  tags:
    - k3s
    - cni

- name: "Install nerdctl"
  ansible.builtin.include_tasks: _k3s_nerdctl.yml
  tags:
    - k3s
    - nerdctl

...
