---

- name: Get timedatectl information
  command: timedatectl
  register: timedatectl_status
  ignore_errors: yes

- include: timedatectl.yml
  when: timedatectl_status.rc is defined and timedatectl_status.rc == 0

- include: linking_tz.yml
  when: timedatectl_status.rc is defined and timedatectl_status.rc != 0

...
