---

- name: Get timedatectl information
  command: timedatectl
  register: timedatectl_status
  ignore_errors: yes

- ansible.builtin.include_tasks: timedatectl.yml
  when: timedatectl_status.rc is defined and timedatectl_status.rc == 0

- ansible.builtin.include_tasks: linking_tz.yml
  when: timedatectl_status.rc is defined and timedatectl_status.rc != 0

...
