---

galaxy_info:
  author: Felix Kazuya, macwinnie
  description: Deploy Preconfigured Docker-Compose-Files without Ansible docker-compose

  license: CC-BY

  min_ansible_version: 2.0

  platforms:
   - name: Ubuntu
     versions:
      - all

  galaxy_tags: []

dependencies: []

...
