#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
###

- hosts: 'wireguard:!localhost'
  become: yes
  order: inventory
  serial:
    - 1

  tasks:
    - name: 'Rollout Wireguard and “SubSpace” as GUI'
      include_role:
        name: wireguard_server

...
