---

install_docker:

  prerequisites:
    - name: 'apt-transport-https'
    - name: 'ca-certificates'
    - name: 'curl'
    - name: 'gnupg2'
    - name: 'software-properties-common'
    - name: 'python3-pip'

  tools:
    - name: 'docker-ce'
    - name: 'docker-ce-cli'
    - name: 'docker-compose-plugin'

  aws_templates:
    - src:  'aws-logger.conf.j2'
      dest: '/etc/docker/aws-logger.conf'
    - src:  'docker-defaults.j2'
      dest: '/etc/default/docker'

package_state: 'latest'

docker_registry: ''

compose_bin_location: '/usr/local/bin/docker-compose'

...
