---

- name: install WireGuard
  become: true
  block:
    - name: install the latest version of basic toolset
      ansible.builtin.package:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - "wireguard"

    - name: install the latest version of basic toolset
      ansible.builtin.package:
        name: "{{ item }}"
        state: "absent"
      with_items:
        - "dnsmasq"

    - name: Add modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - "wireguard"
        - "iptable_nat"
        - "ip6table_nat"

    - ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - "net.ipv4.ip_forward"
        - "net.ipv6.conf.all.forwarding"

    - name: Rollout WireGuard manager UI as Docker container
      ansible.builtin.import_role:
        name: docker_stack
      vars:
        stack: "{{ wireguard_ui_stack }}"

    - name: Deploy WireGuard UI service files to host to restart
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
        - "wgui.path"
        - "wgui.service"

    - name: Enable and start Wireguard UI services
      ansible.builtin.service:
        state: "started"
        enabled: true
        name: "{{ item }}"
      with_items:
        - "wgui.path"
        - "wgui.service"
        - "wg-quick@wg0.service"


...
